/**
 * Pure Java JFC (Swing 1.1) application.
 * This application realizes a windowing application.
 *
 * This file was automatically generated by
 * Omnicore CodeGuide.
 */

package com.builder.uk.watchme;

import java.lang.management.ManagementFactory;
import javax.management.MBeanServer;
import javax.management.ObjectName;

public class WatchMe
{
	private MBeanServer mbs=null;
	
	public static void main(String[] args)
	{
		
		WatchMe watchMe=new WatchMe();
	}
	
	WatchMeBean smb;
	
	public WatchMe()
	{
		mbs=ManagementFactory.getPlatformMBeanServer();
	
		smb=new WatchMeBean();
		Thread t=new Thread(smb);
		t.start();
		
		try
		{
			ObjectName myname=new ObjectName("WatchMeBean:name=watchme");
			mbs.registerMBean(smb,myname);
		}
		catch (Exception e) { e.printStackTrace(); }
		
		WatchMeFrame watchMeFrame = new  WatchMeFrame();
		watchMeFrame.setWatchMeBean(smb);
	
		watchMeFrame.pack();
		watchMeFrame.setVisible(true);
	}
	
}

